#!/bin/sh
CUR_DIR_ABS=$(cd $(dirname $0); pwd)
export PERL_CPANM_HOME=$CUR_DIR_ABS/setup
perl -Iextlib/lib/perl5 cpanm -L extlib --installdeps .

# Create giblognet-shell script
CURRENT_PERL=`which perl`
echo '#!/bin/sh' > script/giblognet-shell
echo -n "$CURRENT_PERL $CUR_DIR_ABS/script/giblognet-shell-raw" >> script/giblognet-shell
echo ' $*' >> script/giblognet-shell
chmod 755 script/giblognet-shell
