version: "3"

services:
  giblognet:
    image: yuki-kimoto/giblognet:latest
    container_name: giblognet
    hostname: giblognet
    restart: always
    ports:
      - "10020:10020"
      - "0.0.0.0:2222:22"
    volumes:
      - giblognet:/home/giblognet
      - sshd:/etc/ssh

volumes:
   giblognet:
   sshd:
